# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:

  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: 127.0.0.1
  port: 5432
  database: oppd
  pool: 5
  timeout: 5000


test:
  adapter: oracle_enhanced
  #encoding: unicode
  username: dbopp
  password: ORACLE
  #host: 127.0.0.1
  #port: 1521
  database: //oracledbdes:1521/dbdes
  pool: 5
  timeout: 5000

production:
    adapter: postgresql
    encoding: unicode
    username: postgres
    password: password
    host: 127.0.0.1
    port: 5432
    database: oppp
    pool: 5
    timeout: 5000
